config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :blog_posts do
    resource :cover_image, only: [:destroy], module: :blog_posts
    resource :video, only: [:destroy], module: :blog_posts
  end
  

  root 'blog_posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    
    has_one_attached :video
    has_one_attached :cover_image
    has_rich_text :content
    
    validates :title, presence: true
    validates :content, presence: true

    scope :sorted, -> { order(arel_table[:published_at].desc.nulls_first).order(updated_at: :desc) }
    scope :draft, -> { where(published_at: nil) }
    scope :published, -> { where("published_at <= ?", Time.current) }
    scope :schedule, -> { where("published_at > ?", Time.current) }

    def draft?
        published_at.nil?
    end

    def published?
        published_at? && published_at <= Time.current
    end

    def scheduled?
        published_at? && published_at > Time.current
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  # :registerable, 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/controllers/blog_posts/cover_images_controller.rb
class BlogPosts::CoverImagesController < ApplicationController
    
    include ActionView::RecordIdentifier

    before_action :authenticate_user!
    before_action :set_blog_post

    def destroy
        @blog_post.cover_image.purge_later

        respond_to do |format| 
           format.html { redirect_to edit_blog_post_path(@blog_post) }
           format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(@blog_post, :cover_image)) }
        end
    end

    private

    def set_blog_post
        @blog_post = BlogPost.find(params[:blog_post_id])
    end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
    def index 
        @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted
        @pagy, @blog_posts = pagy(@blog_posts, items: 3 )
        rescue Pagy::OverflowError
            redirect_to root_path(page: 1)  
           
            # params[:page] = 1
            # retry
    end

    def show
    end

    def new 
        @blog_post = BlogPost.new
    end

    def create
        @blog_post = BlogPost.new(blog_post_params)
        if @blog_post.save
            redirect_to @blog_post
        else
            render :new, status: :unprocessable_entity
        end

    end

    def edit
    end

    def update
        if @blog_post.update(blog_post_params)
            redirect_to @blog_post
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @blog_post.destroy
        redirect_to root_path
    end

    private 
    def blog_post_params
        params.require(:blog_post).permit(:title, :content, :cover_image, :video, :published_at)
    end

    def set_blog_post
        @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : @blog_post = BlogPost.published.find(params[:id])
        rescue ActiveRecord::RecordNotFound
        redirect_to root_path
    end
#test 1
#test 2
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post do |form| %>
    <% if form.object.errors.any?%>
        <div>
         <% form.object.errors.full_messages.each do |message| %>
            <div> <%= message %> </div>    
        <% end %>
        </div>
    <%end%>

    <div class="flex items-center mb-4">
        <div class="w-1/5">
            <%= form.label :title, class: "font-bold " %>
        </div>
        <div class="w-4/5">
            <%= form.text_field :title, class: "w-full rounded-lg border-gray-200 align-top shadow-sm sm:text-sm", placeholder: "Enter your title..." %>
        </div>    
    </div>

    <div class="flex my-8">
        <div class="w-1/5">
            <%= form.label :content, class: "font-bold" %>
        </div>
        <div class="w-4/5">
            <%= form.rich_text_area :content, class:"my-4 w-full rounded-lg border-gray-200 align-top shadow-sm sm:text-sm", placeholder:"Enter any additional order notes...", id: "OrderNotes", rows: "4" %>
        </div>
    </div>

    <div class="flex">
        <div class="w-1/5">
            <%= form.label :cover_image, class: "font-bold"%>
        </div>    
        <div class="w-4/5">
            <% if @blog_post.cover_image.present? %>
            <%= link_to "Remove cover image", blog_post_cover_image_path(blog_post), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow  no-underline" %> 
            <% end %>
            <%= form.file_field :cover_image %>
            <% if @blog_post.cover_image.present? %>
                    <%= image_tag @blog_post.cover_image, class: "w-1/3 mt-8" %>
            <% end %>
        </div>
    </div>

    <div class = "flex mt-8">
        <div class="w-1/5">
            <%= form.label "video:", class: "font-bold" %>
        </div>
        <div class="w-4/5">
            <%= form.file_field :video %>
        </div>
    </div>

    <div class = "flex my-8">
        <div class="w-1/5">
            <%= form.label :published_at, class: "font-bold" %> 
        </div>
        <div class="w-4/5">
            <%= form.datetime_select :published_at, include_blank: true%>
        </div>
    </div>


    <div class="bg-transparent hover:bg-gray-100 text-blue-700 font-semibold py-2 px-4 border border-blue-500 rounded mb-20 w-1/5">
        <%= form.button %> 
    </div>
<%end%>

app/views/blog_posts/edit.html.erb
<h1 class="text-center text-5xl text-orange-500 my-20 font-bold">Edit Blog Post</h1>
<%= render partial: "form", locals: {blog_post: @blog_post} %>
<div  class="inline-block rounded border border-red-600 px-12 py-3 text-sm font-medium text-red-600 hover:bg-gray-100 focus:outline-none focus:ring active:bg-indigo-500 mb-20 w-1/5 " >
    <%= button_to 'Delete', @blog_post, method: :delete, data: {turbo_confirm: "Are you sure?"}%>
</div>

app/views/blog_posts/index.html.erb
<h1 class="text-center text-5xl text-orange-500 my-20 font-bold">My Blog</h1>
<% @blog_posts.each do |blog_post| %>
    <div class="flex h-full group" >    
        <div class="w-1/3 pr-3 h-full">
            <%= video_tag blog_post.video, controls: true, class:"w-full h-full rounded-lg" if blog_post.video.present? %>
        </div>
        <div class="w-2/3 h-full">
            <h2> <%= link_to blog_post.title, blog_post, class: "text-2xl font-medium group-hover:text-red-600" %> </h2>

            <% if blog_post.published_at.present? %>
                <div class="text-sm text-gray-400">
                <%= blog_post.published_at.strftime('%b %d, %Y')%>
                </div>
            <% end %>
            <div class = "my-3">
                <%= truncate(strip_tags(blog_post.content.to_s),  length: 200) %>
            </div>
            
            <% if blog_post.draft? %>
                <div class = "p-2 rounded bg-gray-100 text-gray-900 my-3">Draft</div>
            <% elsif blog_post.scheduled? %>
                <div class = "p-2 rounded bg-blue-100 text-blue-900 my-3">Schedule</div>
            <% end %>
        </div>
    </div>
    <hr class="my-8 border-t border-gray-200">
<% end %>    

<% if @pagy.count > @pagy.items%>
<div class="flex justify-center my-16">
    <%== pagy_nav(@pagy) %>
</div>
<%end%>

app/views/blog_posts/new.html.erb
<h1 class="text-center text-5xl text-orange-500 my-20 font-bold">New Blog Post</h1>

<%= render partial: "form", locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<div class="flex items-center justify-center h-screen">
  <div class="mb-auto">
    <h1 class="text-3xl font-bold mt-4 mb-2 text-center"> <%= @blog_post.title %> </h1>
    <%= image_tag @blog_post.cover_image, class: "mx-auto" if @blog_post.cover_image.present? %>
    <div class="mx-auto">
      <%= @blog_post.content %>
    </div>
    <%= link_to "Edit", edit_blog_post_path(@blog_post), class: "my-20 no-underline inline-block rounded border border-current px-8 py-3 text-sm font-medium text-indigo-600 transition hover:scale-110 hover:shadow-xl focus:outline-none focus:ring active:text-indigo-500" if user_signed_in? %>
  </div>    
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render partial: "shared/navbar"%>
    <div class = 'mx-auto w-3/5' >  
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="bg-gray-800">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex flex-shrink-0 items-center">
          <%= link_to root_path do %>
            <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
          <% end %>
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <%= link_to "Home", root_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"%>
            <% if user_signed_in? %>
                <%= link_to "Create New Blog Post", new_blog_post_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"%>
            <% end %>      
          </div>
        </div>
      </div>


      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <div class="relative ml-3">
          <div>
            <div>
                <% if user_signed_in? %>
                    <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"%>
                <% else %>
                    <%= link_to "Log in", new_user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"%>
                <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  
</nav>